# Generated by Django 5.0 on 2023-12-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblogApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="photos/blog"),
        ),
    ]
