# Generated by Django 5.0 on 2023-12-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblogApp", "0003_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["date_added"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="date_posted",
            new_name="date_added",
        ),
    ]
