# Generated by Django 5.0 on 2023-12-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblogApp", "0004_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date_added"]},
        ),
    ]
