# Generated by Django 5.0 on 2023-12-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblogApp", "0005_alter_post_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
